server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: infraccionService
              uri: lb://infraccionService
              predicates:
                - Path=/adm-infracciones/api/v1/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
